server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      httpclient:
        connect-timeout: 60000
        response-timeout: 60s
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest